### ISSUE TITLE
Production Ready?

### ISSUE THREAD

**Issue by andrewkittredge** [Excel-DNA/IntelliSense#6]
Guys-

This is great.  I plugged it into Calcbench's ExcelDNA AddIn today and it worked without a hitch.  I tested it in Excel 2010 (32 bit) and 2013 (64 bit) on Windows 7, looking for somebody with Vista and Windows 8 boxes.

Do you think it is ready for production?  We have a good number of users using our AddIn in any number of environments.  Needless to say I am not asking for a legal guarantee. @Ron-Ldn , is Excel-DNA/IntelliSense in production at your company?

Thanks for all the hard work,

Andrew

**Comment by Ron-Ldn** [comment]
Hi Andrew,
No, the IntelliSense project is not in production in my firm yet. Actually, I just fixed a few bugs last week.
So you tested it with Excel 2010 and it was all ok ? On my side, I have noticed that the argument help is not well synchronized with the arguments typed, when editing into a cell. But it works fine when editing from the formula bar. With Excel 2013, it looks good.
I think we need to do more testing before being confident for a production release. Could you tell us more about what you tested ? Do your Excel sessions have other add-ins enabled (using or not using ExcelDNA) ?
Thanks for your contribution
Ron

**Comment by Ron-Ldn** [comment]
There still is one big question : where will the final IntelliSense stand and how to activate it ?
Currently we have a separate xll file. But on my side, I don't want to enable a second add-in on my user's Excel. Because then there would be other questions : what if the IntelliSense add-in was already registered ? When do we unregister the add-in ? And who does unregister it ? 

I see different options :
- IntelliSense is part of the core ExcelDNA, and is always activated
- IntelliSense is part of the core ExcelDNA, but is activated by the final add-in using some api we might introduce
- IntelliSense is part of a separate dll. Then we could have the ExcelDna.IntelliSense.xll, but we could also add some api to let the final add-in enable it.

Does anyone reading this have a preference or suggestion ?
Govert, what do you think ?

**Comment by Ron-Ldn** [comment]
Finally, I'd like to introduce some ways for the final add-in to get control over the IntelliSense. It would be optional. I am not sure yet of what I want exactly. 
However, this could be a second version to be released later.

**Comment by govert** [comment]
This is difficult. It seems like the IntelliSense service (whatever code provides that) needs to be shared between all add-ins in the process. It doesn't help to say we put this in the 'core Excel-DNA', since every add-in has its own copy of the Excel-DNA libraries anyway, we have to resolve the interaction whether this is a .dll that every interested add-in references, or whether it is part of ExcelDna.Integration.

So I liked the idea of having it as a separate add-in that any other loaded add-in might register with to provide the IntelliSense services. I understand that it's nicer to just give one add-in with everything in. But it makes cooperation much harder.

The prototype shared AppDomain story seems like the best plan in the other direction. With that plan, many different add-ins might incorporate the IntelliSense 'driver', and the driver would somehow find the 'active' IntelliSense provider, and register with it. If there is no 'active' one, the driver itself becomes the active one.

The main problem with this is versioning - what if the 'active' driver is an old version of the IntelliSense? Another problem is if the 'active' driver gets reloaded etc. - does another add-in then take over the role of being 'active', or do we just live with IntelliSense being broken after that? And the whole scheme sounds too non-deterministic. a lot of things depend on the exact load order.

It thins context, I'm not sure what the 'final add-in' is that should be allowed to 'get control over IntelliSense' for the whole Excel session. The IntelliSense scheme is more likely to work in the long run if different add-ins are forced to play well together. Otherwise it will be this escalating battle of add-ins disabling each others' IntelliSense features with various tricks.

So I guess I'd still prefer a completely separate add-in that provides the IntelliSense service. Then it's easier to manage the versions, and the 'client' add-ins don't have to do anything special to get IntelliSense - I've already built some calls into ExcelDna.Integration that will allow the IntelliSense add-in to get the basic registration info from any Excel-DNA add-in.

But I don't think it's completely resolved yet.

**Comment by govert** [comment]
Otherwise, I'm still not sure the basic UI Automation code is stable enough to call it 'production'. Things break, lock up, stop working or crash Excel at unexpected times.

But that's quite vague. Finding and writing up any specific issues would be a help.

**Comment by Ron-Ldn** [comment]
Whatever we decide, we will need to test it on much bigger add-ins than the ones included in that solution. I will test it on my main project, which has so many use cases, but for the moment I think this is premature.

Following the discussion about the shared AppDomain, I have made it such as the driver does not actually belong to the add-in which created it. 
One add-in will create it and the next ones will just "subscribe" to it. The driver keeps a list of existing add-ins, and when one add-in is unloaded, it "unsubscribes" from it. Then the driver will count the remaining add-ins and will stop and dispose if there is no more add-in left.
I have tested with only 2 add-ins (the ones included in the solution), by adding and removing them in a random order. It worked as expected. But this was a very small test though.

About the versioning issue, won't we have the same problems with the standalone ?
The AppDomain name could be version dependent. I mean, every add-ins using IntelliSense v1.2.3 would share the same AppDomain ; the add-ins using v1.2.4 will use another one. In the end we might have multiple instances of IntelliSense, but it will be rare, and I don't expect to have more than 2 in the same session.

If we go with the standalone, then what could be the life cycle of this add-in ? 
My main add-in is launched through an application (and I am sure this is not an isolate use-case). I can make it check whether the ExcelDNA-IntelliSense is registered, and register it if it is not. But how can my add-in decide to unregister it or not when unloading ? I can't be sure of what other add-ins are running within the session.

I must admit I am quite focused on my own needs and use-cases. It would be helpful to get opinions from other ExcelDNA users.

**Comment by govert** [comment]
I agree we need a lot more testing.

I don't think the AppDomain you make from your add-in can outlive your add-in being unloaded. So I'm not sure in what sense the AppDomain doesn't 'belong' to that add-in. But I'm not sure it's a problem for the IntelliSense to be hosted by one add-in - it solves some problems and makes others, so it's a trade-off.

My point with the versioning is that an Excel instance should only have one IntelliSense provider. Having more than one library listening to the UI Automation stuff will become a mess. But then you can't have a v1.2.3 and v1.2.4 loaded at the same time. So if the v1.2.3 add-in loads first, you get that experience, and the add-in which wants to load v1.2.4 loses (but only on machines with the other add-in loaded).

If it were standalone, it would be clear that there is only add-in that provides of IntelliSense stuff, and the user can update it to a new version, or at least see what version they have.

I don't feel too strongly about the details this, as long as we have some plan (which the AppDomain story is a huge help towards putting in place).

(I haven't tried your code with the new threading - it sounds like a big improvement!)

**Comment by Ron-Ldn** [comment]
Well, I invite you to give it a try ! :)

Perhaps we should start working on the test cases. I am thinking about having multiple add-ins with a lot of functions, and gather them into 2 or 3 groups. Each group will have its own instance of the IntelliSense.
Then let's see how Excel behaves. Perhaps we will have good or bad surprises (ok, this is Excel, so I am not that optimistic...). 
At least this would give us more concrete cases for this discussion.

**Comment by andrewkittredge** [comment]
Thank you for update.  Yes, it worked fine in Excel 2010.  I basically just opened up our AddIn (if you sign up for a trial account on calcbench.com you can install it) in Excel 2010 and 2013 and verified that the IntelliSense was working.

I was launching my AddIn from Visual Studio and did not realize that Intellisense would not work when I bundled my AddIn into an .msi.  

I am not qualified to give an opinion on the architecture but I think developers will be more likely to use IntelliSense if does not complicate their bundling and installation process.  I suspect I am not the only Excel-DNA developer for whom their company's AddIn is the first and last desktop .net program they work on.

Sorry I am not more help but I offer my services as a tester and cheerleader.

**Comment by govert** [comment]
I've finally sorted out enough of the internal architecture to start early testing.
A very early 'alpha' release is now available: https://github.com/Excel-DNA/IntelliSense/releases/tag/v0.1-alpha

**Comment by Ron-Ldn** [comment]
Hi Govert. 

I have added it to the development version of my add-in so my coworkers can test it as well. I will remove it before the next release to production. 

I noticed that the 64bit version does not work. I will investigate later and eventually open an issue.

Another note: my add-in is launched via a command "Excel /x myAddin.xll ExcelDna.IntelliSense.xll". It works fine. However, if I start a debugging session with Visual Studio using such a command line, then I get into an infinite loop of pop-ups coming from Visual Studio telling me that the "Managed Debugging Assistant 'LoaderLock' has detected a problem in 'C\Program Files\...\EXCEL.EXE'. Additional Information: Attempting managed execution inside OS Loader Lock. Do not attempt to run managed code inside a DllMain or image initialization function since doing so can cause the application to hang.". Are you aware of this? Shall I open a new issue about it?
I can debug my add-in without the IntelliSense, but I just wonder whether there is a more serious issue behind.

**Comment by govert** [comment]
The LoaderLock warning is correct, in that the IntelliSense add-in is indeed running managed code in the DLL loader context. I've tried to be careful to not do anything dangerous there, so you should be able to safely disable this warning. I would definitely want to know if you find that Excel hangs, of course.

Thank you also for checking on the 64-bit side. I don't have a 64-bit Excel at hand, so will need to get that set up on a VM again.

Everything is also in place for the library version (referencing and loading from your add-in rather than having a separate .xll). I've worked out my old concerns about how different instances will coordinate. But that needs some checking and testing too. So for now that basic 32-bit .xll version is the one I'm most interested in getting feedback on.

**Comment by govert** [comment]
@Ron-Ldn The 64-bit version should work now: https://github.com/Excel-DNA/IntelliSense/releases/tag/v0.1-alpha7 (at least under Excel 2013).
If not, please let me know.

**Comment by Ron-Ldn** [comment]
Hi Govert,
I tested briefly in the following environments and all look good:
- Win7, Excel 2010 32bit
- Win7, Excel 2013 32bit
- Win7, Excel 2013 64bit
I will do more testing next week though.

**Comment by andrewkittredge** [comment]
Hi Govert,
I tested briefly in the following environments and all look good:

- Win 10, Excel 2016 32bit

**Comment by govert** [comment]
@andrewkittredge Thanks for the report. I've had one issue reported in that configuration - that as Excel is closing (after having loaded the IntelliSense), a kind of 'ghost' window pops up for a moment.

Have you seen anything like this?

**Comment by andrewkittredge** [comment]
I'm nitpicking here but text rendering in the tool-tip is a little weird on my screen.  Specifically the opening and closing parenthesis overrun the function arguments.  See the attached screen shot. 
![intellisense_font](https://cloud.githubusercontent.com/assets/430274/15442552/fc78eeae-1eaf-11e6-9732-33e383285c37.png)

**Comment by govert** [comment]
@andrewkittredge That's terrible! I've made some changes (to check in soon) that will fix the bottom of that window (where things are cut off). But I haven't seen the argument width going wrong before. I'll look out for it.

**Comment by andrewkittredge** [comment]
Making the font size bigger did not really help.  Did you choose Font("Segoe UI", 9, FontStyle.Italic) } to conform to Microsoft's look and feel?

**Comment by govert** [comment]
Which font size? Did it do harm?
Yes - I tried to pick the same font and size as my Excel 2013.

**Comment by Ron-Ldn** [comment]
Hi Govert,
Just to let you know that my team has been playing with the latest version since 3 weeks without any issue. I don't believe we were always focused on the intellisense pop-up when doing our work, but at least it was stable. No crash, no memory issue observed.
I must remove it for now because we are preparing a release. 
Let me know when you have a new version so we will test it again.
Reminder: we tested under the following environments
Win7, Excel 2010 32bit
Win7, Excel 2013 32bit
Win7, Excel 2013 64bit

**Comment by andrewkittredge** [comment]
FWIW we just shipped our Add-in with IntelliSense enabled.  Thanks @govert  and friends.
